default: # 默认连接
  host: "121.36.9.185"
  port: 10086
  logging: false
  username: "root"
  password: "anpengyu1"
  type: "mysql"
  database: "tally"
  synchronize: true
  entities: ["app/entity/*.ts","app/entity/*/*.ts"]